### ISSUE TITLE
on Ubuntu bionic beaver, it will fail to install because of Java 10

### ISSUE THREAD

**Issue by tychay** [geerlingguy/ansible-role-elasticsearch#36]
[elasticsearch does not support Java 9 or 10](https://stackoverflow.com/questions/49623648/logstash-with-java10-get-error-unrecognized-vm-option-useparnewgc/51275818), which is the default on Ubuntu.

I believe the solution is just to have it install java 8

```
roles:
    - role: geerlingguy.java
      java_packages:
        - openjdk-8-jdk
    - geerlingguy.elasticsearch
```

(not tested, I don't think you need to make a change, just document the dependency in the readme).

**Comment by tychay** [comment]
Okay tested. I needed a single task after the java role and before the elasticsearch role

```
---
---
# c.f. https://github.com/elastic/ansible-elasticsearch/blob/master/tasks/java.yml for redhat
- name: Get the installed java path (for ubuntu)
  shell: "update-alternatives --display java | grep '^/' | awk '{print $1}' | grep java-8 | head -1"
  become: yes
  register: java_full_path
  failed_when: False
  changed_when: False
- name: set java alternatives to 1.8
  alternatives:
    name: java
    path: "{{ java_full_path.stdout }}"
    link: /usr/bin/java
```
