### ISSUE TITLE
Beware: apt_key does not respect apt proxy settings

### ISSUE THREAD

**Issue by mohclips** [geerlingguy/ansible-role-elasticsearch#47]
Not really a bug with this code, but more a gotcha.

https://github.com/geerlingguy/ansible-role-elasticsearch/blob/master/tasks/setup-Debian.yml#L8

You will need to do something like this...
```
- role: geerlingguy.elasticsearch
  environment:
      # required as the apt_key module doesnt use the apt proxy settings, Doh!!
      http_proxy: "http://{{ proxy_ip }}:{{ proxy_port }}/"
      https_proxy: "http://{{ proxy_ip }}:{{ proxy_port }}/"  # HTTPS URI not supported by ansible
```
