### ISSUE TITLE
Unable to pin elasticsearch package versions

### ISSUE THREAD

**Issue by PuppetNinja** [geerlingguy/ansible-role-elasticsearch#51]
with snippets like below
```yaml
- name: Install Elasticsearch.
  package:
    name: elasticsearch
    state: "{{ elasticsearch_package_state }}"
```
there is no way to pin specific versions of elasticsearch, this is not very handy for keeping versions of elk stack nodes with consistent versions
